---
title: Veni Vidi Codi
description: Ahmet Sait's Software Blog
author: Ahmet Sait

links:
  github: ahmetsait
  gitlab: ahmetsait
  linkedin: ahmetsait
  stackoverflow: users/3624513/ahmet-sait?tab=profile
  atom: feed # just type anything here for a working RSS icon

collections:
  posts_en:
    permalink: /blog/en/:title
    output: true
  posts_tr:
    permalink: /blog/tr/:title
    output: true

# Atom Feed Config
feed:
  path: "" # This seems to work fine for disabling default feed
  collections:
    posts_en:
      path: blog/en/venividicodi.atom
    posts_tr:
      path: blog/tr/venividicodi.atom

defaults:
  -
    scope:
      path: ""
    values:
      layout: main
      lang: en
  -
    scope:
      path: _posts_en
      type: posts_en
    values:
      layout: post
      lang: en
  -
    scope:
      path: blog/en
    values:
      lang: en
  -
    scope:
      path: _posts_tr
      type: posts_tr
    values:
      layout: post
      lang: tr
  -
    scope:
      path: blog/tr
    values:
      lang: tr

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass

# Handling Reading
safe: false
include:
  - .htaccess
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: false

# Filtering Content
show_drafts: false
limit_posts: 0
future: false
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
page_excerpts: true
excerpt_separator: "\n\n"
incremental: false

# Serving
#detach: false
#port: 4000
host: 0.0.0.0
baseurl: "" # the subpath of your site, e.g. /blog
show_dir_listing: false

# Outputting
permalink: /blog/:title
paginate_path: /blog/page/:num
timezone: Asia/Istanbul

quiet: false
verbose: false

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
